### ISSUE TITLE
[BUG] Cron not working since 1.4.5-r0-ls89

### ISSUE THREAD

**Issue by kilrah** [linuxserver/docker-rsnapshot#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cron tasks haven't been executed since this update.
Also manually running rsnapshot <schedule> does not output to docker console anymore.

### Steps To Reproduce

Cron timings set in crontabs/root. Saw there's a crontabs/abc file now, tried moving the contents to it with no change.

### Environment

```markdown
- OS: Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A, official ghcr.io/linuxserver/rsnapshot
```

### Container logs

```bash
Nothing of use


usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

***** Upgrading config file if required *****
/etc/rsnapshot.conf file is already up to date.
***** Validating config file *****
Syntax OK
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
```

**Comment by thespad** [comment]
We had an issue with the base image that broke downstream cron jobs, it's been fixed and I've trigged a manual build of the rsnapshot image which should incorporate those fixes.

**Comment by kilrah** [comment]
Fix confirmed working, thanks!

**Comment by wassereimer86** [comment]
I have the same problem. Latest update from the container was 5 days ago and my cron tasks haven't been executed since 11/19.

linuxserver/rsnapshot latest 1729f355edc1 5 days ago
