### ISSUE TITLE
[FEAT] Option to print crond (and thus rsnapshot) logs 

### ISSUE THREAD

**Issue by Ezwen** [linuxserver/docker-rsnapshot#16]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like some way for this container to print all rsnapshot-related logs directly in the container output logs, instead of only printing in `/config/rsnapshot.log`.

### Reason for change

The benefit is to be able to learn about the container behavior/health the same way as any other container, ie. using the `docker logs` command, instead of having to read a specific file.

### Proposed code change

It is a little confusing to me how linuxserver manages its containers' entrypoints, but I think this can be done by simply changing options given to the `crontab` foreground process.

**Comment by homerr** [comment]
It seems to me as if you may be able to do this, but I don't think it is to do with the crontab. You could try commenting out the log file line in the `rsnapshot.conf` file, and then see if you are getting output in the docker log. You may need to increase verbosity to level 3 to achieve this (also in the config file). If it is crontab based, again you can modify this as it's in the `/config` directory that you can modify (and have to). 

I don't use the container and it's a bit too much for me to set up to test, so this would be my advice.

Given this is quite niche, I'm not going to add this option in but if you're handy with script it may be worth publishing a docker mod for this container, if it's not a case of modifying the commands in the crontab/config file. 

Discord is quite lively if you want to dig into the container a bit more.
